import axios from "axios";
import authHeader from "./auth-header";
import { API_URL } from "~/config/axios";

const STATE_LIST = [
  {
    zip: "501",
    zipcodename: "HOLTSVILLE, NY",
    city: "HOLTSVILLE",
    state: "NY",
    countyname: "SUFFOLK",
    id: 1,
  },
  {
    zip: "1001",
    zipcodename: "AGAWAM, MA",
    city: "AGAWAM",
    state: "MA",
    countyname: "HAMPDEN",
    id: 2,
  },
  {
    zip: "1002",
    zipcodename: "AMHERST, MA",
    city: "AMHERST",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 3,
  },
  {
    zip: "1003",
    zipcodename: "AMHERST, MA",
    city: "AMHERST",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 4,
  },
  {
    zip: "1004",
    zipcodename: "AMHERST, MA",
    city: "AMHERST",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 5,
  },
  {
    zip: "1005",
    zipcodename: "BARRE, MA",
    city: "BARRE",
    state: "MA",
    countyname: "WORCESTER",
    id: 6,
  },
  {
    zip: "1007",
    zipcodename: "BELCHERTOWN, MA",
    city: "BELCHERTOWN",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 7,
  },
  {
    zip: "1008",
    zipcodename: "BLANDFORD, MA",
    city: "BLANDFORD",
    state: "MA",
    countyname: "HAMPDEN",
    id: 8,
  },
  {
    zip: "1009",
    zipcodename: "BONDSVILLE, MA",
    city: "BONDSVILLE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 9,
  },
  {
    zip: "1010",
    zipcodename: "BRIMFIELD, MA",
    city: "BRIMFIELD",
    state: "MA",
    countyname: "HAMPDEN",
    id: 10,
  },
  {
    zip: "1011",
    zipcodename: "CHESTER, MA",
    city: "CHESTER",
    state: "MA",
    countyname: "HAMPDEN",
    id: 11,
  },
  {
    zip: "1012",
    zipcodename: "CHESTERFIELD, MA",
    city: "CHESTERFIELD",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 12,
  },
  {
    zip: "1013",
    zipcodename: "CHICOPEE, MA",
    city: "CHICOPEE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 13,
  },
  {
    zip: "1014",
    zipcodename: "CHICOPEE, MA",
    city: "CHICOPEE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 14,
  },
  {
    zip: "1020",
    zipcodename: "CHICOPEE, MA",
    city: "CHICOPEE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 15,
  },
  {
    zip: "1021",
    zipcodename: "CHICOPEE, MA",
    city: "CHICOPEE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 16,
  },
  {
    zip: "1022",
    zipcodename: "CHICOPEE, MA",
    city: "CHICOPEE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 17,
  },
  {
    zip: "1026",
    zipcodename: "CUMMINGTON, MA",
    city: "CUMMINGTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 18,
  },
  {
    zip: "1027",
    zipcodename: "EASTHAMPTON, MA",
    city: "EASTHAMPTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 19,
  },
  {
    zip: "1028",
    zipcodename: "EAST LONGMEADOW, MA",
    city: "EAST LONGMEADOW",
    state: "MA",
    countyname: "HAMPDEN",
    id: 20,
  },
  {
    zip: "1029",
    zipcodename: "EAST OTIS, MA",
    city: "EAST OTIS",
    state: "MA",
    countyname: "BERKSHIRE",
    id: 21,
  },
  {
    zip: "1030",
    zipcodename: "FEEDING HILLS, MA",
    city: "FEEDING HILLS",
    state: "MA",
    countyname: "HAMPDEN",
    id: 22,
  },
  {
    zip: "1031",
    zipcodename: "GILBERTVILLE, MA",
    city: "GILBERTVILLE",
    state: "MA",
    countyname: "WORCESTER",
    id: 23,
  },
  {
    zip: "1032",
    zipcodename: "GOSHEN, MA",
    city: "GOSHEN",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 24,
  },
  {
    zip: "1033",
    zipcodename: "GRANBY, MA",
    city: "GRANBY",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 25,
  },
  {
    zip: "1034",
    zipcodename: "GRANVILLE, MA",
    city: "GRANVILLE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 26,
  },
  {
    zip: "1035",
    zipcodename: "HADLEY, MA",
    city: "HADLEY",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 27,
  },
  {
    zip: "1036",
    zipcodename: "HAMPDEN, MA",
    city: "HAMPDEN",
    state: "MA",
    countyname: "HAMPDEN",
    id: 28,
  },
  {
    zip: "1037",
    zipcodename: "HARDWICK, MA",
    city: "HARDWICK",
    state: "MA",
    countyname: "WORCESTER",
    id: 29,
  },
  {
    zip: "1038",
    zipcodename: "HATFIELD, MA",
    city: "HATFIELD",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 30,
  },
  {
    zip: "1039",
    zipcodename: "HAYDENVILLE, MA",
    city: "HAYDENVILLE",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 31,
  },
  {
    zip: "1040",
    zipcodename: "HOLYOKE, MA",
    city: "HOLYOKE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 32,
  },
  {
    zip: "1041",
    zipcodename: "HOLYOKE, MA",
    city: "HOLYOKE",
    state: "MA",
    countyname: "HAMPDEN",
    id: 33,
  },
  {
    zip: "1050",
    zipcodename: "HUNTINGTON, MA",
    city: "HUNTINGTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 34,
  },
  {
    zip: "1053",
    zipcodename: "LEEDS, MA",
    city: "LEEDS",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 35,
  },
  {
    zip: "1054",
    zipcodename: "LEVERETT, MA",
    city: "LEVERETT",
    state: "MA",
    countyname: "FRANKLIN",
    id: 36,
  },
  {
    zip: "1056",
    zipcodename: "LUDLOW, MA",
    city: "LUDLOW",
    state: "MA",
    countyname: "HAMPDEN",
    id: 37,
  },
  {
    zip: "1057",
    zipcodename: "MONSON, MA",
    city: "MONSON",
    state: "MA",
    countyname: "HAMPDEN",
    id: 38,
  },
  {
    zip: "1059",
    zipcodename: "NORTH AMHERST, MA",
    city: "NORTH AMHERST",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 39,
  },
  {
    zip: "1060",
    zipcodename: "NORTHAMPTON, MA",
    city: "NORTHAMPTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 40,
  },
  {
    zip: "1061",
    zipcodename: "NORTHAMPTON, MA",
    city: "NORTHAMPTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 41,
  },
  {
    zip: "1062",
    zipcodename: "FLORENCE, MA",
    city: "FLORENCE",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 42,
  },
  {
    zip: "1063",
    zipcodename: "NORTHAMPTON, MA",
    city: "NORTHAMPTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 43,
  },
  {
    zip: "1066",
    zipcodename: "NORTH HATFIELD, MA",
    city: "NORTH HATFIELD",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 44,
  },
  {
    zip: "1068",
    zipcodename: "OAKHAM, MA",
    city: "OAKHAM",
    state: "MA",
    countyname: "WORCESTER",
    id: 45,
  },
  {
    zip: "1069",
    zipcodename: "PALMER, MA",
    city: "PALMER",
    state: "MA",
    countyname: "HAMPDEN",
    id: 46,
  },
  {
    zip: "1070",
    zipcodename: "PLAINFIELD, MA",
    city: "PLAINFIELD",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 47,
  },
  {
    zip: "1071",
    zipcodename: "RUSSELL, MA",
    city: "RUSSELL",
    state: "MA",
    countyname: "HAMPDEN",
    id: 48,
  },
  {
    zip: "1072",
    zipcodename: "SHUTESBURY, MA",
    city: "SHUTESBURY",
    state: "MA",
    countyname: "FRANKLIN",
    id: 49,
  },
  {
    zip: "1073",
    zipcodename: "SOUTHAMPTON, MA",
    city: "SOUTHAMPTON",
    state: "MA",
    countyname: "HAMPSHIRE",
    id: 50,
  },
];

export const getAllStates = ({
  page,
  limit,
}: {
  page: number;
  limit: number;
}) => {
  return STATE_LIST;
};

export const Get = (zip: number) => {
  return axios.get(API_URL + `/States/${zip}`, {
    headers: authHeader(),
  });
};

export const Create = (data: any) => {
  return axios.post(API_URL + "/Note/Create", data, {
    headers: authHeader(),
  });
};

export const Modify = (id: string, data: any) => {
  return axios.put(API_URL + `/Note/update?id=${id}`, data, {
    headers: authHeader(),
  });
};

export const Delete = (id: number) => {
  return axios.delete(API_URL + `/Note/${id}`, {
    headers: authHeader(),
  });
};
